{
 "title": "tid2_srv6_20250121",
 "time": { "from": "2025-01-21T12:00:41.767Z", "to": "2025-01-21T12:10:41.767Z" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "NE", "query": { "query": "label_values(source)" } },
   { "name": "Interface", "query": { "query": "label_values(interface_name)" } },
   {
    "name": "network_instance",
    "query": {
     "query": "label_values(network_instance_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "srv6 fsa topology telemetry",
   "type": "andrewbmchugh-flow-panel",
   "gridPos": { "h": 23, "w": 13, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "gnmic_sros_port_oper_state_oper_state",
     "legendFormat": "oper-state:{{source}}:{{interface_name}}"
    },
    {
     "expr": "rate(gnmic_sros_port_stats_out_octets[30s])*8",
     "legendFormat": "{{source}}:{{interface_name}}:out"
    },
    {
     "expr": "rate(gnmic_sros_port_stats_in_octets[30s])*8",
     "legendFormat": "{{source}}:{{interface_name}}:in"
    }
   ]
  },
  {
   "title": "Port Throughput IN",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(gnmic_sros_port_stats_in_octets[30s])*8 > 100000",
     "legendFormat": "{{source}} - {{interface_name}} IN"
    }
   ]
  },
  {
   "title": "Port Throughput OUT",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 11, "x": 13, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(gnmic_sros_port_stats_out_octets[30s])*8 > 100000",
     "legendFormat": "{{source}} - {{interface_name}} OUT"
    }
   ]
  },
  {
   "title": "IP WAN Throughput IN",
   "type": "timeseries",
   "gridPos": { "h": 19, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(gnmic_sros_if_ip_stats_in_octets{source=~\"$NE\",interface_name=~\"$Interface\"}[30s])*8",
     "legendFormat": "{{source}} - {{interface_interface_name}} IN"
    }
   ]
  },
  {
   "title": "IP WAN Throughput OUT",
   "type": "timeseries",
   "gridPos": { "h": 19, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(gnmic_sros_if_ip_stats_out_octets{source=~\"$NE\",interface_name=~\"$Interface\"}[30s])*8",
     "legendFormat": "{{source}} - {{interface_interface_name}} OUT"
    }
   ]
  },
  {
   "title": "v6 WAN Throughput IN",
   "type": "timeseries",
   "gridPos": { "h": 19, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(gnmic_sros_if_v6_stats_in_octets{source=~\"$NE\",interface_name=~\"$Interface\"}[30s])*8",
     "legendFormat": "{{source}} - {{interface_interface_name}} IN"
    }
   ]
  },
  {
   "title": "v6 WAN Throughput OUT",
   "type": "timeseries",
   "gridPos": { "h": 19, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(gnmic_sros_if_v6_stats_out_octets{source=~\"$NE\",interface_name=~\"$Interface\"}[30s])*8",
     "legendFormat": "{{source}} - {{interface_interface_name}} OUT"
    }
   ]
  },
  {
   "title": "SRv6 policy endpoint stats",
   "type": "timeseries",
   "gridPos": { "h": 19, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(gnmic_sros_srpolicy_egress_stats_byte_count{source=~\"$NE\"}[30s])*8",
     "legendFormat": "{{source}} - {{sr_policy_egress_statistics_endpoint}}"
    }
   ]
  },
  {
   "title": "v4 WAN Throughput OUT",
   "type": "timeseries",
   "gridPos": { "h": 19, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(gnmic_sros_if_v4_stats_out_octets{source=~\"$NE\",interface_name=~\"$Interface\"}[30s])*8",
     "legendFormat": "{{source}} - {{interface_interface_name}} OUT"
    }
   ]
  },
  {
   "title": "BGP IPv4 Routing Stats",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 80 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "gnmic_sros_bgp_ipv4_routes_remote_active_routes{router_router_name=~\"$network_instance\",source=~\"$NE\"}",
     "legendFormat": "{{source}}, Active Routes"
    }
   ]
  },
  {
   "title": "BGP IPv6 Routing Stats",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 80 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "gnmic_sros_bgp_ipv6_routes_remote_active_routes{router_router_name=\"Base\",source=~\"$NE\"}",
     "legendFormat": "{{source}} Active Routes"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "gnmic_sros_cpu_cpu_usage{source=~\"$NE\"}",
     "legendFormat": "{{source}} Total Instant"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "gnmic_sros_mem_in_use {source=~\"$NE\"}",
     "legendFormat": "{{source}} free mem"
    }
   ]
  }
 ]
}